-- MySQL Workbench Synchronization
-- Generated: 2020-05-05 01:41
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Esteban Manrique

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE TABLE IF NOT EXISTS `tarea8_compaaerea`.`EMPLEADO_PARTICIOA_VUELO` (
  `Código Empleado` VARCHAR(10) NOT NULL,
  `# de vuelo` VARCHAR(7) NOT NULL,
  `Fecha` DATE NOT NULL,
  `Código Avión` VARCHAR(30) NOT NULL,
  `# tripulación` INT(3) NOT NULL,
  INDEX `fk_EMPLEADO_PARTICIOA_VUELO_EMPLEADO1_idx` (`Código Empleado` ASC) ,
  INDEX `fk_EMPLEADO_PARTICIOA_VUELO_VUELO1_idx` (`# de vuelo` ASC, `Fecha` ASC) ,
  INDEX `fk_EMPLEADO_PARTICIOA_VUELO_AVION1_idx` (`Código Avión` ASC) ,
  CONSTRAINT `fk_EMPLEADO_PARTICIOA_VUELO_AVION1`
    FOREIGN KEY (`Código Avión`)
    REFERENCES `tarea8_compaaerea`.`AVION` (`Código Avión`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLEADO_PARTICIOA_VUELO_EMPLEADO1`
    FOREIGN KEY (`Código Empleado`)
    REFERENCES `tarea8_compaaerea`.`EMPLEADO` (`Código Empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLEADO_PARTICIOA_VUELO_VUELO1`
    FOREIGN KEY (`# de vuelo` , `Fecha`)
    REFERENCES `tarea8_compaaerea`.`VUELO` (`# de vuelo` , `Fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLEADO_PARTICIOA_VUELO_VUELO2`
    FOREIGN KEY (`# de vuelo` , `Fecha`)
    REFERENCES `tarea8_compaaerea`.`VUELO` (`# de vuelo` , `Fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
